<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Attempt;
use Doctrine\ORM\EntityRepository;

/**
 * ResultRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttemptRepository extends EntityRepository
{
    public function getPointsByAttempt(Attempt $attempt){
       return $this->getEntityManager()
            ->createQuery(
                "SELECT SUM(answer.points) FROM AppBundle:UserAnswer u
                INNER JOIN u.answer answer
                WHERE u.attempt=".$attempt->getId()
            )
            ->getResult()[0][1];
    }
}
