<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Quiz;
use Doctrine\ORM\EntityRepository;

/**
 * ResultRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuizRepository extends EntityRepository
{
    public function getPointsByQuiz(Quiz $quiz)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT SUM(answer.points) FROM AppBundle:Answer answer
                    INNER JOIN answer.question question
                    INNER JOIN question.quiz quiz
                    WHERE quiz.id='.$quiz->getId()
            )
            ->getResult()[0][1];
    }
}